---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - ./namespace.yaml
  - github.com/metallb/metallb/config/crd?ref=v0.14.9
  - github.com/metallb/metallb/config/rbac?ref=v0.14.9
  - github.com/metallb/metallb/config/controllers?ref=v0.14.9
  - github.com/metallb/metallb/config/webhook?ref=v0.14.9
