---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
transformers:
  - labels.yaml
resources:
  - namespace.yaml
  # - cilium/install.yaml
  - coredns/install.yaml
  - csi-driver-nfs/install.yaml
  - reloader/install.yaml
  - metrics-server/install.yaml
