---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cilium/install.yaml
  - coredns/install.yaml
  - csi-driver-nfs/install.yaml
  # - external-secrets/install.yaml
  - metrics-server/install.yaml
