# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: infra-apps-traefik-certificates
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: infra-apps-cert-manager
#       namespace: flux-system
#     - name: infra-apps-cert-manager-issuers
#       namespace: flux-system
#   path: ./infrastructure/base/networking/traefik/certificates
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-apps-traefik
  namespace: flux-system
spec:
  path: ./infrastructure/base/networking/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: infra-apps-traefik-extras
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: infra-apps-traefik
#       namespace: flux-system
#     - name: infra-apps-traefik-certificates
#       namespace: flux-system
#   path: ./infrastructure/base/networking/traefik/extras
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
