---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components: []
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  # - github.com/grafana/grafana-operator/deploy/kustomize/overlays/cluster_scoped?ref=v5.20.0
  # Flux-Kustomizations
  - alertmanager/install.yaml
  - alloy/install.yaml
  - blackbox-exporter/install.yaml
  - fluent-bit/install.yaml
  - gatus/install.yaml
  - goldilocks/install.yaml
  - grafana/install.yaml
  - kube-prometheus-stack/install.yaml
  - loki/install.yaml
  - miscellaneous
  - node-exporter/install.yaml
  - victoria-logs/install.yaml
