---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "dev0ps-duckdns-org-production"
  namespace: networking
spec:
  secretName: "dev0ps-duckdns-org-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "dev0ps.duckdns.org"
  dnsNames:
    - "dev0ps.duckdns.org"
    - "*.dev0ps.duckdns.org"
