---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "dev0ps-duckdns-org-staging"
  namespace: networking
spec:
  secretName: "dev0ps-duckdns-org-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "dev0ps.duckdns.org"
  dnsNames:
    - "dev0ps.duckdns.org"
    - "*.dev0ps.duckdns.org"
