---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
transformers:
  - labels.yaml
# remember to add the base resources to the cluster specific kustomization files
resources:
  - cert-manager/install.yaml
  - dbms
  - default
  - external-secrets/install.yaml
  - istio-system
  - keda
  - kube-system
  - kube-tools
  - networking
  - observability
