---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
transformers:
  - labels.yaml
components:
  - ../components
# remember to add the base resources to the cluster specific kustomization files
resources:
  - github.com/dxas90/common//common?ref=v0.2.0
  - cert-manager
  # - dbms
  - default
  # - kube-system
#  - networking
  - observability
