---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
transformers:
  - labels.yaml
components:
  - ../components
# remember to add the base resources to the cluster specific kustomization files
resources:
  - cert-manager
  - dbms
  - default
  - external-secrets
  - istio-system
  - keda
  - kube-system
  - kube-tools
#  - networking
  - observability
