---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter-scrape
spec:
  staticConfigs:
    - targets:
        - "todo-1:9100"
        - "todo-2:9100"
        - "todo-3:9100"
  metricsPath: /metrics
  scheme: HTTP
  relabelings:
    - action: replace
      targetLabel: job
      replacement: node-exporter
