---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./helmrepository.yaml
  - ./dnsendpoint-crd.yaml
  - ./helmrelease.yaml
  # - ./dnsendpoint.yaml
