---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../components
resources:
  # - ../common/cert-manager
  # - ../common/dbms
  # - ../common/default
  # - ../common/external-secrets
  - github.com/dxas90/common//common/istio-system?ref=v0.2.0
  # - ../common/keda
  - ../common/kube-system
  # - ../common/kube-tools
  # - ../common/networking
  - ../common/observability
  - ./playground
