---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../components
resources:
  # - ../common/cert-manager
  # - ../common/dbms
  # - ../common/default
  - github.com/dxas90/common//common?ref=v0.6.0
  # - ../common/kube-system
  # - ../common/networking
  # - ../common/observability
  - ./playground
