upstream-base-url: "https://ntfy.sh"
base-url: "https://ntfy.example.com"

cache-file: "/var/cache/ntfy/cache.db"
cache-duration: 2h
attachment-cache-dir: "/var/cache/ntfy/attachments"

behind-proxy: true
keepalive-interval: "45s"

log-level: info
log-format: json
